name: Generate Release & Publish to TS

on:
  push:
    tags: "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Use checkout to publish the files in your repo
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore and Build
        run: |
          dotnet restore --locked-mode
          dotnet tool restore
          dotnet build
      
      - name: Release
        uses: softprops/action-gh-release@v2

        with:
          generate_release_notes: true
          make_latest: "true"
          files: |
            src/Joeverhood/bin/Debug/Joeverhood.dll
            libs/ILUtils/ILUtils.dll
            LICENSE.md
